;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     ______      __
;    / ________  / ____  __________
;   / /   / __ \/ / __ \/ ___/ ___/
;  / /___/ /_/ / / /_/ / /  (__  )
;  \____/\____/_/\____/_/  /____/
;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[colors]
background = #0F232B
foreground = #FFE0EB

color0 = #0F232B
color1 = #E64A4A
color2 = #48C74E
color3 = #F2C335
color4 = #1A8ED9
color5 = #FF82A9
color6 = #00D2FF
color7 = #FFE0EB
color8 = #5B7582
color9 = #FF6B6B
color10 = #62E368
color11 = #FFDF70
color12 = #43A9EB
color13 = #FFA4C2
color14 = #40E2FF
color15 = #FFFFFF
dark-light = #1A323D 
active-light = #2C4A57
